spring.application.name=cab-book-user

app.instance-id:c1

server.port=8084

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=user-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.client-id=${app.instance-id}
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
spring.kafka.consumer.properties.schema.registry.url=http://localhost:8081
spring.kafka.consumer.properties.json.value.type=com.pragat.cab_book_user.LocationEvent

# Cooperative rebalancing (incremental, less disruptive)
spring.kafka.consumer.properties.partition.assignment.strategy=org.apache.kafka.clients.consumer.CooperativeStickyAssignor
spring.kafka.consumer.properties.group.instance.id=${app.instance-id}

# Bound how many records you process per poll (prevents huge batches)
spring.kafka.consumer.properties.max.poll.records=10

# Give enough time for long processing without being kicked out
spring.kafka.consumer.properties.max.poll.interval.ms=300000


# cab-book-user ALSO needs producer config for DLT publishing
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
spring.kafka.producer.properties.schema.registry.url=http://localhost:8081

# Producer transactions (for sending output + committing offsets atomically)
spring.kafka.producer.transaction-id-prefix=cab-user-tx-

# Read only committed transactional output
spring.kafka.consumer.properties.isolation.level=read_committed


#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=1s


